### ISSUE TITLE
A strongly-named assembly is required

### ISSUE THREAD

**Issue by plindjo** [KennanChan/Revit.Async#13]
Hi and thanks for creating a great library!
I've used the nuget package for a while without any errors. But now I am on a new PC and trying to use it on a new project (with Revit 2020), and I get a FileLoadException stating that the Revit assemblies or dependencies could not be loaded:
![StronglyTypedAssemblyRequired](https://user-images.githubusercontent.com/18084211/137262258-93372c4b-c536-455d-b0ee-517ef498d487.PNG)

I have tried all versions on nuget and get the same exception with them all. I don't know if this is a problem on my computer or something else but I can't figure out how to resolve it or investigate it further. I even tried placing Revit 2016 DLLs along side the addin and add an AssebmlyResolve but without any luck.
Any ideas are greatly appreciated. Thanks

**Comment by KennanChan** [comment]
It seems a problem with the latest version of Revit.Async. A strong name was asigned to Revit.Async.dll but RevitAPIUI.dll was not signed with strong name. That's not allowed. I will soon publish a new release to get rid of the strong name signing
