### ISSUE TITLE
Is there a way to trigger the SaveFamilyCommand() with a MouseEventArgs ?

### ISSUE THREAD

**Issue by MathieuJsrd** [KennanChan/Revit.Async#15]
Hi,
Thanks a lot for this awesome repo!

The title is my question :
Is there a way to trigger the SaveFamilyCommand() with a MouseEventArgs ?

In the current case, the trigger is the TestWindow Button to save a family.
I would like to change the trigger with a MouseEventArgs but because the SaveFamilyCommand is a ICommand class, I have some trouble achieving this...

**Comment by KennanChan** [comment]
I failed to get the point of "trigger the SaveFamilyCommand with a MouseEventArgs". Could you pls be more specific?

**Comment by KennanChan** [comment]
If you are using UI events to drive your application(like a winform application), you can definitely use Revit.Async in the event handler to call Revit APIs. In this way you just care nothing about the ICommand abstraction or the WPF command mechanism.
