### ISSUE TITLE
IExternalApplication Implementation 

### ISSUE THREAD

**Issue by RyanPatrickDaley** [KennanChan/Revit.Async#18]
I'm not getting Revit.Async to work, and I think it might be because I am trying to implement it within an IExternalApplication instead of an IExternalCommand.  I tried to start a simple method within RevitTask.RunAsync(), and it never finishes running.   So in this sample method, I never reach the second line of code:

```
private async void SelectInRevit()
{
 await RevitTask.RunAsync(
      UIApp =>
      {
          UIApp.ActiveUIDocument.Selection.SetElementIds(SelectedFam.ElementIds);
      });
SelectionChangeable = !SelectionChangeable; 
}
```

**Comment by KennanChan** [comment]
Have you initialize RevitTask in the entry of your application or command?
```csharp
RevitTask.Initialize(app);
```

**Comment by RyanPatrickDaley** [comment]
Yea, that was in fact the problem.  Now it is working!
