### ISSUE TITLE
RevitTask.RunAsync() returns before Revit 

### ISSUE THREAD

**Issue by RyanPatrickDaley** [KennanChan/Revit.Async#19]
The await RevitTask.RunAsync() does not seem to wait for Revit to finish.  In the below sample method, RevitTask.RunAsync() returns "Jimmy" before the Selection is set in the ActiveUiDocument.  So my MessageBox shows "jimmy" before the selection is made.  I'm not sure why this would be the case.

```
private async void SelectInRevit()
        {
            var myString = await RevitTask.RunAsync(
                app =>
                {
                    app.ActiveUIDocument.Selection.SetElementIds(SelectedFam.ElementIds);
                    return "jimmy"; 
                });
            MessageBox.Show($"{myString}");
        }
```

**Comment by KennanChan** [comment]
How about calling document.Regenerate() right after setting selected elements.

**Comment by RyanPatrickDaley** [comment]
Okay, this is an interested suggestion to include a doc.Regenerate() call inside of a Transaction because the API docs say that .Regenerate() is automatically called when a transaction is committed
https://www.revitapidocs.com/2015/22468e2c-9772-8478-0816-c9759aa43428.htm

But in any case, it still doesn't seem to await the Revit part of the method to finish.  It returns "Jimmy" and continues.

```
private async void SelectInRevit()
{
    if(SelectedFam != null)
    {
        var myString = await RevitTask.RunAsync(
            app =>
            {
                using (Transaction t = new Transaction(app.ActiveUIDocument.Document, "SettingSelected"))
                {
                    t.Start("SettingSelected");
                    app.ActiveUIDocument.Selection.SetElementIds(SelectedFam.ElementIds);
                    app.ActiveUIDocument.Document.Regenerate(); 
                    t.Commit();
                }                            
                return "Jimmy";
            });
        myString += " Boy";
    }               
}
```

**Comment by KennanChan** [comment]
The Selection.SetElementIds() might be async internally although it returns void. RevitTask doesn't aware of that and just returns when the api call finishes. You might need to find another way to check if the elements are visually selected to continue.

**Comment by KennanChan** [comment]
You can try to write a pure external event handler to test the code to see if the issue still exists

**Comment by KennanChan** [comment]
I think I can close this issue. You can submit a new one if the issue persists.
