### ISSUE TITLE
Getter for UIApplication

### ISSUE THREAD

**Issue by denizmaral** [KennanChan/Revit.Async#24]
You can initialise the UIApplication in RevitTask class. It would be nice to get the uiApp from that static class because I would not have to pass for all windows and commands commandData. I pass for now UIControlledApplication in OnStartUp.

**Comment by KennanChan** [comment]
I don't get what you mean by "You can initialise the UIApplication in RevitTask class". Can u provide more detail?

**Comment by KennanChan** [comment]
Actually you can get the UIApplication instance from `RevitTask.RunAsync` method, just like what you do with `IExternalEventHandler.Execute` method

**Comment by denizmaral** [comment]
Thank you very much for quick reply. I mean, in order to use UIApplication in windows etc. I have to pass it from ExternalCommand. 
![image](https://github.com/KennanChan/Revit.Async/assets/55183821/d35b5e09-7ef4-4051-9084-7d04494715c7)

In OnStartUp I implemented that 
`            // For Async-Transactions pass the application
            Revit.Async.RevitTask.Initialize(application);`

I would like to then get application variable through whole Application so as not to pass it for all commands.

**Comment by denizmaral** [comment]
I hope I explained it well :) 
It would be a nice helper to get uiApp if it was initialised. With doing that I won't have to worry about pass variable to all methods in all commands. For now I have to create for all windows a parameter with UIApplication and then I pass it to ViewModel to be able to create my ViewModel

**Comment by KennanChan** [comment]
You can get the instance of UIApplication by calling 
```csharp
RevitTask.RunAsync((uiApplication) => {
   // your code here
})
```
This way the instance of UIApplication is provided by Revit calling `IExternalEventHandler.Execute` method. For Revit.Async, it is not a good practise to hold an instance of UIAppliation and expose a getter.

**Comment by KennanChan** [comment]
In my point of view, it is good for memory management by getting an instance of UIApplication from `IExternalEventHandler.Execute` or `RevitTask.RunAsync` instead of passing it everywhere, because these are all local variables which is friendly to garbage collection.

**Comment by denizmaral** [comment]
Thank you very much for replies and support. Revit.Async is a great tool and I'm very happy to use it!
