### ISSUE TITLE
Need to Invoke after RevitTask.RunAsync?

### ISSUE THREAD

**Issue by michaelcsikos** [KennanChan/Revit.Async#31]
Firstly, let me say this is a very impressive library, and an incredible time saver.

After calling `await RevitTask.RunAsync(app =>...)`  I expected the context to continue on the UI thread, however, it appears it does not.

Doing something simple like 'btnSave.Enabled = false' throws

`Cross-thread operation not valid: Control 'btnSave' accessed from a thread other than the thread it was created on.`

Apart from using `Invoke` is there a way to force `RunAsync()` to return to the UI context?

**Comment by michaelcsikos** [comment]
Or do we have to wrap all of the remaining UI-related code with `RevitTask.RunAsync`?

**Comment by KennanChan** [comment]
To run ui code on the ui main thread, you need to use the asynchronous pattern the ui framework provides.

For WPF, use `this.Dispatcher.Invoke()`
For windows form, use `this.Invoke()`

**Comment by KennanChan** [comment]
Is this issue resolved?

**Comment by KennanChan** [comment]
I'll close it first. Fire another one in case there is still a problem
