### ISSUE TITLE
Revit async Hangs at Waithelper

### ISSUE THREAD

**Issue by Khush-Chaudhary** [KennanChan/Revit.Async#32]
public override int Wait(IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)
{
	if (_dispatcher._disableProcessingCount > 0)
	{
		return UnsafeNativeMethods.WaitForMultipleObjectsEx(waitHandles.Length, waitHandles, waitAll, millisecondsTimeout, bAlertable: false);
	}
	return SynchronizationContext.WaitHelper(waitHandles, waitAll, millisecondsTimeout);
}

RevitAsync Hangs at WaitHelper

Context: I am running A WPF UI and from my viewModel i am calling a function 

private void GetFamilyTypes()
{ 
    FamilyType = FamilyHelpers.GetFamilyTypesNamesAsync(SelectedFamilyName);
}

public static ObservableCollection<string> GetFamilyTypesNamesAsync(string familyName)
{
    Task<(bool isLoaded, Family family)> obj = LoadFamilyByFamilyNameAsync(familyName);
    obj.Wait();
    bool isLoaded = obj.Result.isLoaded;
    Family family = obj.Result.family;

    if (!isLoaded || family == null)
    {
        return null;
    }
    ObservableCollection<string> familyTypes = new ObservableCollection<string>();
    family.GetFamilySymbolIds().ToList().ForEach(x => familyTypes.Add(family.Document.GetElement(x).Name));
    return familyTypes;
}

public async static Task<(bool isLoaded, Family family)> LoadFamilyByFamilyNameAsync(string familyName)
{
    bool isLoaded = false;
    Family family = null;

    string path = Properties.Settings.Default.FamilyHangerPath;
    List<string> allpaths = FileHelper.GetAllFilePathsBasedOnExtension(path, "*.rfa");
    foreach (string filePath in allpaths)
    {
        if (FileHelper.GetFileName(filePath) == familyName)
        {
            family = await RevitTask.RunAsync(() =>
            {
                bool result = CommonData.Instance.Doc.LoadFamily(filePath, out Family loadedFamily);
                if (result)
                {
                    return loadedFamily;
                }
                return null;
            });
            isLoaded = family != null;
            break;
        }
    }
    return (isLoaded, family);
}

now in loadFamilyByNameAsync RevitTask.RunASync hangs

I have also tried to use app to get Document instead of using my singleton class

**Comment by KennanChan** [comment]
```
LoadFamilyByFamilyNameAsync(familyName).ContinueWith((task) => {
     var result = task.Result;
     //update the result to your ObservableCollection
})
```
